services:
  frontend:
    build: ./apps/client
    ports:
      - "8000:8000"

  backend:
    build: ./apps/api
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=imslite

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: imslite
    ports:
      - "5432:5432"